name: MGArcade
main: com.comze_instancelabs.mgarcade.Main
version: 1.2.1
author: InstanceLabs
softdepend: [Vault, MinigamesLib]
depend: [MinigamesLib]
loadbefore: [MinigamesLib]
commands:
   mg:
      description: Main command
      usage: /mg [action]
      aliases: [mgarcade, mga, arcade]
